### ISSUE TITLE
Removal of fake-crypto-material.zip breaks the "stack deployment" step of the tutorial

### ISSUE THREAD

**Issue by chris-zimm** [carbynestack/base-images#4]
Pre-generated offline material has been removed...

**Comment by strieflin** [comment]
Hi @chris-zimm, thank you very much. We will update the tutorial with a link to the revision of the repo, where the archive with the tuples still was available. If you have time to submit a PR, very welcome!

**Comment by sbckr** [comment]
@chris-zimm please use the following link to download the fake crypto material:
https://github.com/carbynestack/base-images/raw/3595c5427915b2f9e1f22804e3f742cda9e72312/fake-crypto-material.zip

**Comment by chris-zimm** [comment]
Thanks, @strieflin and @sbckr!  I already created a PR for correcting the link on the website

**Comment by strieflin** [comment]
Resolved by carbynestack/carbynestack.github.io#60.
