### ISSUE TITLE
Remove tuples from MP-SPDZ image

### ISSUE THREAD

**Issue by strieflin** [carbynestack/base-images#8]
Currently, the MP-SPDZ image contains insecure pre-generated tuples. As soon as carbynestack/ephemeral#6 is resolved, they should be removed.

**Comment by sbckr** [comment]
The two most resent releases 
- [0.5](https://github.com/carbynestack/base-images/releases/tag/0.4), based on [carbynestack/MP-SPDZ](https://github.com/carbynestack/MP-SPDZ) commit [5350e66](https://github.com/carbynestack/MP-SPDZ/commit/5350e664c203e6a9340db10c2b9d686bef02451b) with PRNG option
  ```bash
  docker pull ghcr.io/carbynestack/spdz:5350e66_no-offline
  ```
- [0.6](https://github.com/carbynestack/base-images/releases/tag/0.6), based on [data61/MP-SPDZ](https://github.com/data61/MP-SPDZ) commit [642d11f](https://github.com/data61/MP-SPDZ/commit/642d11f7dd99f6a5f5298090def695aeee906223)
  ```bash
  docker pull ghcr.io/carbynestack/spdz:642d11f_no-offline
  ```
do both no longer contain pre-generated tuples.
